### ISSUE TITLE
Request for datasets used

### ISSUE THREAD

**Issue by Kimsterz** [alejandECE/air-noise#2]
Hi Sir, 

I'm Noorhakim from the Singapore Institute of Technology. 

I'm also doing a similar study on the relationship between aircraft noise and the complaint data.

Am I able to get a copy of the datasets that you used?

Thank you so much. 

Yours Sincerely,
Noorhakim

**Comment by alejandECE** [comment]
Please contact me by email and tell me a little bit more about your project. Thanks

**Comment by Kimsterz** [comment]
Hi Mr Luis,



To answer your question, my project interest lies in the 3 objectives
below.



1)      Understand the community location distribution for aircraft noise
complaints and hidden patterns

2)      Discover the relationship between time parameter and aircraft
noise. The seasonal pattern should be highlighted

3)      Describe all the findings and explain potential reasons. Other
datasets can be used as a support



Currently, the dataset that I have from the SFO Noise Abatement Office does
not give me a complete picture as to why or what triggers sudden spikes in
complaints received.



I would like to find out, if possible with your dataset, some correlations
(ie. at what dB would it trigger someone to lodge a complaint).



If you would require further clarification, please do not hesitate to
contact me.



I look forward to hearing from you.



Yours Sincerely,

Noorhakim
